[run]
skip-files = ['routes/assets.go', 'utils/update_sql_from_api.go']
timeout    = '2m'

# SA1029 â€“ Inappropriate key in call to context.WithValue
# https://staticcheck.io/docs/checks#SA1029
[[issues.exclude-rules]]
linters = 'staticcheck'
text    = 'SA1029:'

[linters]
disable-all = true
enable = [
    'asciicheck',
    'bodyclose',
    'deadcode',
    'depguard',
    'dogsled',
    'dupl',
  # 'errcheck',
  # 'errorlint',
    'exhaustive',
  # 'exhaustivestruct',
    'exportloopref',
    'forbidigo',
  # 'funlen',
    'gci',
  # 'gochecknoglobals',
  # 'gochecknoinits',
  # 'gocognit',
  # 'goconst',
  # 'gocritic',
  # 'gocyclo',
  # 'godot',
  # 'godox',
    'goerr113',
    'gofmt',
    'goheader',
    'gofumpt',
    'goimports',
  # 'golint',
    'gomodguard',
  # 'gomnd',
    'goprintffuncname',
  # 'gosec',
    'gosimple',
    'govet',
    'ineffassign',
    'interfacer',
  # 'lll',
    'makezero',
    'maligned',
    'misspell',
  # 'nakedret',
  # 'nestif',
  # 'nlreturn',
    'noctx',
    'nolintlint',
  # 'paralleltest',
  # 'prealloc',
    'rowserrcheck',
  # 'scopelint',
  # 'sqlclosecheck',
    'staticcheck',
    'structcheck',
    'stylecheck',
  # 'testpackage',
    'thelper',
    'tparallel',
    'typecheck',
    'unconvert',
    'unparam',
    'unused',
    'varcheck',
    'whitespace',
  # 'wrapcheck',
  # 'wsl',
]
