[run]
skip-files = ['routes/assets.go']

[linters]
disable-all = true
enable = [
    'bodyclose',
    'deadcode',
    'gofumpt',
    'goimports',
    'gosimple',
    'govet',
    'ineffassign',
    'rowserrcheck',
    'staticcheck',
    'structcheck',
    'typecheck',
    'unconvert',
    'unparam',
    'unused',
    'varcheck',
]
