# Categories in alpha order, trophies in difficulty then alpha order.

# Date Specific

[['Date Specific']]
name        = 'Happy Birthday, Code Golf'
emoji       = 'ğŸ‚'
description = 'Solve any hole on <a href=//github.com/code-golf/code-golf/commit/4b44>2 Oct</a>.'

[['Date Specific']]
name        = 'Independence Day'
emoji       = 'ğŸ‡ºğŸ‡¸'
description = 'Solve <a href=/united-states>United States</a> on <a href=//www.wikipedia.org/wiki/Independence_Day_(United_States)>4 Jul</a>.'

[['Date Specific']]
name        = 'Pi Day'
emoji       = 'ğŸ¥§'
description = 'Solve <a href=/Ï€>Ï€</a> on <a href=//www.wikipedia.org/wiki/Pi_Day>14 Mar</a>.'

[['Date Specific']]
name        = 'Twelvetide'
emoji       = 'ğŸ…'
description = 'Solve <a href=/12-days-of-christmas>12 Days of Christmas</a> during <a href=//www.wikipedia.org/wiki/Twelvetide>25 Dec â€“ 5 Jan</a>.'

[['Date Specific']]
name        = 'Vampire Byte'
emoji       = 'ğŸ§›'
description = 'Solve <a href=/vampire-numbers>Vampire Numbers</a> on <a href=//www.wikipedia.org/wiki/Halloween>31 Oct</a>.'

# GitHub

[[GitHub]]
name        = 'My God, Itâ€™s Full of Stars'
emoji       = 'â­'
description = 'Star <a href=//github.com/code-golf/code-golf>the Code Golf repository</a>.'

[[GitHub]]
name        = 'Patches Welcome'
emoji       = 'ğŸ’¾'
description = 'Contribute a merged PR to <a href=//github.com/code-golf/code-golf>the Code Golf repository</a>.'

# Hole/Lang Specific

[['Hole/Lang Specific']]
name        = 'Interview Ready'
emoji       = 'ğŸ’¼'
description = 'Solve <a href=/fizz-buzz>Fizz Buzz</a>.'

[['Hole/Lang Specific']]
name        = 'Caffeinated'
emoji       = 'â˜•'
description = 'Solve any hole in both Java and JavaScript.'

[['Hole/Lang Specific']]
name        = 'COBOWL'
emoji       = 'ğŸ³'
description = 'Solve <a href=/ten-pin-bowling#cobol>Ten-pin Bowling in COBOL</a>.'

[['Hole/Lang Specific']]
name        = 'ElePHPant in the Room'
emoji       = 'ğŸ˜'
description = 'Solve any hole in PHP.'

[['Hole/Lang Specific']]
name        = 'Inception'
emoji       = 'ğŸ§ '
description = 'Solve <a href=/brainfuck#brainfuck>brainfuck in brainfuck</a>.'

[['Hole/Lang Specific']]
name        = 'Ouroboros'
emoji       = 'ğŸ'
description = 'Solve <a href=/quine#python>Quine in Python</a>.'

[['Hole/Lang Specific']]
name        = 'Tim Toady'
emoji       = 'ğŸª'
description = 'Solve any hole in both Perl and Raku.'

# Miscellaneous

[[Miscellaneous]]
name        = 'Different Strokes'
emoji       = 'ğŸŒˆ'
description = 'Submit unique solutions for bytes and chars on the same hole.'

[[Miscellaneous]]
name        = 'RTFM'
emoji       = 'ğŸ“•'
description = 'Visit the <a href=/about>About page</a>.'

[[Miscellaneous]]
name        = 'Slowcoach'
emoji       = 'ğŸ¦¥'
description = 'Fail any hole by exceeding the time limit.'

[[Miscellaneous]]
name        = 'tl;dr'
emoji       = 'ğŸ§¶'
description = 'Submit a solution that is rejected for being too long.'

# Progression

[[Progression]]
name        = 'Hello, World!'
emoji       = 'ğŸ‘‹'
description = 'Solve your first hole.'

[[Progression]]
name        = 'Up to Eleven'
emoji       = 'ğŸ¸'
description = 'Solve your eleventh hole.'

[[Progression]]
name        = 'Bakerâ€™s Dozen'
emoji       = 'ğŸ'
description = 'Solve your thirteenth hole.'

[[Progression]]
name        = 'The Watering Hole'
emoji       = 'ğŸº'
description = 'Solve your nineteenth hole.'

[[Progression]]
name        = 'Forty Winks'
emoji       = 'ğŸ˜´'
description = 'Solve your fortieth hole.'

[[Progression]]
name        = 'DONâ€™T PANIC!'
emoji       = 'ğŸ‘'
description = 'Solve your forty-second hole.'

[[Progression]]
name        = 'Bullseye'
emoji       = 'ğŸ¯'
description = 'Solve your fiftieth hole.'

[[Progression]]
name        = 'Itâ€™s Over 9000!'
emoji       = 'ğŸ‰'
description = 'Earn over 9,000 points in either bytes or chars scoring.'

#[[Progression]]
#name        = 'Leagues Under the Sea'
#emoji       = 'ğŸ³'
#description = 'Earn 20,000 points in either bytes or chars scoring.'

[[Progression]]
name        = 'Polyglot'
emoji       = 'ğŸ”£'
description = 'Solve any hole in every language.'
