version: '2'
services:
  app:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    env_file: .env  # Used for testing with prod secrets, NEVER committed.
    environment:
      DEV:       1
      PGHOST:    db
      PGSSLMODE: disable
      PGUSER:    code-golf
    pids_limit: 1024
    privileged: true
    ulimits:
      core: -1
    volumes:
      - ..:/go
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: code-golf
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../db:/docker-entrypoint-initdb.d
